service: serverless-hello-world

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 1

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 2
    events:
      - http:
          path: hello/get
          method: get

plugins:
  - serverless-offline
